### ISSUE TITLE
Don't run github actions twice on pull requests

### ISSUE THREAD

**Issue by machow** [machow/siuba#389]
Currently, our CI github triggers github actions on all pushes and pull_request events. The haunting issue with this is that it runs PRs made from branches on this repo twice (Note that for PRs opened from forks it will run once).

```yaml
name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
```

Changing to only run pull requests, and pushes to main works well, if you open draft PRs for all branches you want to test. However, sometimes I want to run github actions while testing things out (not necessarily worth opening a draft PR).

A compromise might be:

**classic approach**

* run on pull request
* run on pushes to main

**customization**

* run on pushes to `dev-*` branches
* workflow dispatch for manually triggering on edge cases

```yaml
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*']
  pull_request:
  release:
    types: [published]
```
